#
# Makefile
# Carles Amigó, 2015-05-15 12:19
#

all:
	~/.gem/ruby/2.1.0/gems/fontcustom-1.3.8/bin/fontcustom compile --no-hash .

clean:
	rm -rf fontcustom .fontcustom-manifest.json

# vim:ft=make
#
